### ISSUE TITLE
Could not import backend for traitsui.  Make sure you have a suitable UI toolkit like PyQt/PySide or wxPython

### ISSUE THREAD

**Issue by Rajat-Mehta** [kuixu/kitti_object_vis#22]
I installed the required libraries and am getting the following error when I try to run 'python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis' command:

```
Traceback (most recent call last):
  File "kitti_object.py", line 943, in <module>
    dataset_viz(args.dir, args)
  File "kitti_object.py", line 706, in dataset_viz
    figure=None, bgcolor=(0, 0, 0), fgcolor=None, engine=None, size=(1000, 500)
  File "/home/rajat/Desktop/Radspot/kitti_object_vis/venv/lib/python3.6/site-packages/mayavi/tools/figure.py", line 64, in figure
    engine = get_engine()
  File "/home/rajat/Desktop/Radspot/kitti_object_vis/venv/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 92, in get_engine
    return self.new_engine()
  File "/home/rajat/Desktop/Radspot/kitti_object_vis/venv/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 137, in new_engine
    check_backend()
  File "/home/rajat/Desktop/Radspot/kitti_object_vis/venv/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 40, in check_backend
    raise ImportError(msg)
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
```

Could you please help me with this? I have installed the packages that you have mentioned in your readme, is there any other package that we need in order to run this code?

**Comment by OmarElzaafaranyBrightskies** [comment]
same here, have you found a solution

**Comment by Rajat-Mehta** [comment]
@OmarElzaafaranyBrightskies you need to install PyQt to run the visualizations being generated in the code. So you can do:
```
pip install pyqt5
```
and it should work for you. @kuixu This package should also be added in the requirements.txt file.

**Comment by qq1120637483** [comment]
> @OmarElzaafaranyBrightskies you need to install PyQt to run the visualizations being generated in the code. So you can do:
> 
> ```
> pip install pyqt5
> ```
> 
> and it should work for you. @kuixu This package should also be added in the requirements.txt file.

you are right

**Comment by kuixu** [comment]
@qq1120637483 Thanks.

**Comment by KangChou** [comment]
but--->same:
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed.
