### ISSUE TITLE
ImportError: Could not import backend for traitsui 

### ISSUE THREAD

**Issue by hitbuyi** [kuixu/kitti_object_vis#53]
Environments:
OS: ubuntu20.04
conda: 4.13.0
mayavi: 4.7.4
vtk: 9.1.0
python:3.9.6

Error messages:

```
(py1121) hitbuyi@hitbuyi-Dell-G15-5511:~/PycharmProjects/pytorch_project/3D_vis$ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis
data/object training
Traceback (most recent call last):
  File "/home/hitbuyi/PycharmProjects/pytorch_project/3D_vis/kitti_object.py", line 982, in <module>
    dataset_viz(args.dir, args)
  File "/home/hitbuyi/PycharmProjects/pytorch_project/3D_vis/kitti_object.py", line 744, in dataset_viz
    fig = mlab.figure(
  File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/figure.py", line 64, in figure
    engine = get_engine()
  File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 92, in get_engine
    return self.new_engine()
  File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 137, in new_engine
    check_backend()
  File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 40, in check_backend
    raise ImportError(msg)
ImportError: Could not import backend for traitsui.  Make sure you
        have a suitable UI toolkit like PyQt/PySide or wxPython
        installed
```

what's the problem?

**Comment by hitbuyi** [comment]
> Environments: OS: ubuntu20.04 conda: 4.13.0 mayavi: 4.7.4 vtk: 9.1.0 python:3.9.6
> 
> Error messages:
> 
> ```
> (py1121) hitbuyi@hitbuyi-Dell-G15-5511:~/PycharmProjects/pytorch_project/3D_vis$ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis
> data/object training
> Traceback (most recent call last):
>   File "/home/hitbuyi/PycharmProjects/pytorch_project/3D_vis/kitti_object.py", line 982, in <module>
>     dataset_viz(args.dir, args)
>   File "/home/hitbuyi/PycharmProjects/pytorch_project/3D_vis/kitti_object.py", line 744, in dataset_viz
>     fig = mlab.figure(
>   File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/figure.py", line 64, in figure
>     engine = get_engine()
>   File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 92, in get_engine
>     return self.new_engine()
>   File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 137, in new_engine
>     check_backend()
>   File "/home/hitbuyi/.conda/envs/py1121/lib/python3.9/site-packages/mayavi/tools/engine_manager.py", line 40, in check_backend
>     raise ImportError(msg)
> ImportError: Could not import backend for traitsui.  Make sure you
>         have a suitable UI toolkit like PyQt/PySide or wxPython
>         installed
> ```
> 
> what's the problem?

I found its my environmental error, not the fault of the code, and found this code runs well in  opencv version < 4.4.x,  opencv 4.5.x may conflicts with PyQt5
