### ISSUE TITLE
kitti-test如何使用测试集进行生成box呢

### ISSUE THREAD

**Issue by youtodohaveyou** [kuixu/kitti_object_vis#61]
你好，作者：

kitti数据集testing的文件结构和github给的一样，我把自己的测试集结果pred 传上去之后执行python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 1 --pred 会报错：Traceback (most recent call last): File "kitti_object.py", line 979, in assert os.path.exists(args.dir + "/" + args.split + "/pred") AssertionError该怎么修改呢？

**Comment by FlyingAnt2018** [comment]
> 你好，作者：
> 
> kitti数据集testing的文件结构和github给的一样，我把自己的测试集结果pred 传上去之后执行python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 1 --pred 会报错：Traceback (most recent call last): File "kitti_object.py", line 979, in assert os.path.exists(args.dir + "/" + args.split + "/pred") AssertionError该怎么修改呢？

你好，为什么我在ubuntu下一直跑不起来？
`Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/qlz/opt/anaconda3/envs/monocon/bin/platforms" ...
loaded library "/home/qlz/opt/anaconda3/envs/monocon/lib/python3.7/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
QObject::moveToThread: Current thread (0x30dd030) is not the object's thread (0x348ed80).
Cannot move to target thread (0x30dd030)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/qlz/opt/anaconda3/envs/monocon/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

已放弃 (核心已转储)`

**Comment by kuixu** [comment]
> 你好，作者：
> 
> kitti数据集testing的文件结构和github给的一样，我把自己的测试集结果pred 传上去之后执行python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 1 --pred 会报错：Traceback (most recent call last): File "kitti_object.py", line 979, in assert os.path.exists(args.dir + "/" + args.split + "/pred") AssertionError该怎么修改呢？

It reports that the directory (args.dir + "/" + args.split + "/pred") not exists. please fix it.

**Comment by kuixu** [comment]
> > 你好，作者：
> > kitti数据集testing的文件结构和github给的一样，我把自己的测试集结果pred 传上去之后执行python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 1 --pred 会报错：Traceback (most recent call last): File "kitti_object.py", line 979, in assert os.path.exists(args.dir + "/" + args.split + "/pred") AssertionError该怎么修改呢？
> 
> 你好，为什么我在ubuntu下一直跑不起来？ `Got keys from plugin meta data ("xcb") QFactoryLoader::QFactoryLoader() checking directory path "/home/qlz/opt/anaconda3/envs/monocon/bin/platforms" ... loaded library "/home/qlz/opt/anaconda3/envs/monocon/lib/python3.7/site-packages/cv2/qt/plugins/platforms/libqxcb.so" QObject::moveToThread: Current thread (0x30dd030) is not the object's thread (0x348ed80). Cannot move to target thread (0x30dd030)
> 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/qlz/opt/anaconda3/envs/monocon/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
> 
> 已放弃 (核心已转储)`

It seems that there is an issue with the Qt platform. You could try to reinstall the OpenCV and qt packages.
