### ISSUE TITLE
Traits error

### ISSUE THREAD

**Issue by Azriro** [kuixu/kitti_object_vis#7]
Why do I get this error? I did every step perfectly :(
`Traceback (most recent call last):
  File "kitti_object.py", line 734, in <module>
    dataset_viz(args.dir, args)
  File "kitti_object.py", line 646, in dataset_viz
    objects_pred, depth, img, constraint_box=args.const_box, save=args.save_depth, pc_label=args.pc_label)
  File "kitti_object.py", line 323, in show_lidar_with_depth
    draw_lidar(pc_velo, fig=fig, pc_label=pc_label)
  File "/home/azri/obj_det/viz_util.py", line 139, in draw_lidar
    mlab.points3d(pc[:,0], pc[:,1], pc[:,2], color, color=pts_color, mode=pts_mode, colormap = 'gnuplot', scale_factor=pts_scale, figure=fig)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/helper_functions.py", line 34, in the_function
    return pipeline(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/helper_functions.py", line 79, in __call__
    output = self.__call_internal__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/helper_functions.py", line 175, in __call_internal__
    g = Pipeline.__call_internal__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/helper_functions.py", line 93, in __call_internal__
    return self.build_pipeline()
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/helper_functions.py", line 121, in build_pipeline
    object = pipe(object, **this_kwargs)._target
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/modules.py", line 154, in __init__
    super(DataModuleFactory, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 161, in __init__
    self.set(**traits)
  File "/usr/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 169, in set
    **traits)
  File "/usr/lib/python2.7/dist-packages/traits/has_traits.py", line 1952, in trait_set
    setattr( self, name, value )
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 170, in error
    value )
traits.trait_errors.TraitError: The 'colormap' trait of a GlyphFactory instance must be 'Accent' or 'Blues' or 'BrBG' or 'BuGn' or 'BuPu' or 'Dark2' or 'GnBu' or 'Greens' or 'Greys' or 'OrRd' or 'Oranges' or 'PRGn' or 'Paired' or 'Pastel1' or 'Pastel2' or 'PiYG' or 'PuBu' or 'PuBuGn' or 'PuOr' or 'PuRd' or 'Purples' or 'RdBu' or 'RdGy' or 'RdPu' or 'RdYlBu' or 'RdYlGn' or 'Reds' or 'Set1' or 'Set2' or 'Set3' or 'Spectral' or 'YlGn' or 'YlGnBu' or 'YlOrBr' or 'YlOrRd' or 'autumn' or 'binary' or 'black-white' or 'blue-red' or 'bone' or 'cool' or 'copper' or 'file' or 'flag' or 'gist_earth' or 'gist_gray' or 'gist_heat' or 'gist_ncar' or 'gist_rainbow' or 'gist_stern' or 'gist_yarg' or 'gray' or 'hot' or 'hsv' or 'jet' or 'pink' or 'prism' or 'spectral' or 'spring' or 'summer' or 'winter', but a value of 'gnuplot' <type 'str'> was specified.
`

**Comment by kuixu** [comment]
@Azriro  Do you still get this error in Python3 ?

**Comment by Azriro** [comment]
I cannot get mayavi to work with Python3. It said ModuleNotFoundError: No module named 'vtkOpenGLKitPython' when I tried to install mayavi

**Comment by kuixu** [comment]
@Azriro Maybe you could try to install it from the source at http://www.vtk.org/download/.

**Comment by Azriro** [comment]
I've already installed mayavi and vtk but the system for some reason couldn't not detect it. I found the vtk folder with vtkOpenGLKitPython but it doesn't seem to read it.

**Comment by Azriro** [comment]
I've solved the vtkOpenGLKitPython error but now it cannot read the data

Traceback (most recent call last):
  File "kitti_object.py", line 734, in <module>
    dataset_viz(args.dir, args)
  File "kitti_object.py", line 584, in dataset_viz
    objects = dataset.get_label_objects(data_idx)
  File "kitti_object.py", line 84, in get_label_objects
    return utils.read_label(label_filename)
  File "/home/azri/obj_det/kitti_util.py", line 358, in read_label
    lines = [line.rstrip() for line in open(label_filename)]
FileNotFoundError: [Errno 2] No such file or directory: 'data/obj/training/label_2/000000.txt'

**Comment by kuixu** [comment]
Great! While, where is your data? You can specify your data folder by `-d` option

**Comment by Azriro** [comment]
Oh sorry, my bad. Yeah, I did it and it works thanks. Sorry I'm new

**Comment by Azriro** [comment]
Sorry to bother, last question. I know that the default dataset is 000000, how to change it and can it use a video rather than an image or it can only use an image?

**Comment by fukatani** [comment]
@Azriro 
If you want to use specific index, please try
`$ python kitti_object.py --show_lidar_with_depth --img_fov --const_box --vis --show_image_with_boxes --ind 100`

**Comment by Azriro** [comment]
ohh okay thank you!

**Comment by dfgan** [comment]
> I've solved the vtkOpenGLKitPython error but now it cannot read the data
> 
> Traceback (most recent call last):
> File "kitti_object.py", line 734, in
> dataset_viz(args.dir, args)
> File "kitti_object.py", line 584, in dataset_viz
> objects = dataset.get_label_objects(data_idx)
> File "kitti_object.py", line 84, in get_label_objects
> return utils.read_label(label_filename)
> File "/home/azri/obj_det/kitti_util.py", line 358, in read_label
> lines = [line.rstrip() for line in open(label_filename)]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/obj/training/label_2/000000.txt'

hi，can you tell me how to solve the vtkOpenGLKitPython error?

**Comment by kuixu** [comment]
@dfgan This pull(https://github.com/kuixu/kitti_object_vis/pull/25) may help you.
